name: Update Server Status

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  status:
    runs-on: self-hosted
    steps:
      - name: Checkout active branch
        uses: actions/checkout@v3
        with:
          ref: active
      - name: Install dependencies
        run: pip install python-a2s
      - name: Run server check script
        run: python scripts/check_servers.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/server_status.json
          git commit -m "Update server status [skip ci]" || exit 0
          git push origin active